// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otoylapoqdhodmuydkor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90b3lsYXBvcWRob2RtdXlka29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzUzMTQsImV4cCI6MjA2ODQ1MTMxNH0.O7sF6226xPJc0APm_0Ms0bVrM_T31LnGiZ2iUSp_c9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});